server:
  port: 9090
spring:
  application:
    name: py-shipping
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13308/shipping?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
jwt-key: HoZfG3GMf87uYTqfO
expire-day: 1
ali-sign-name: 田大立的博客
ali-testing-sign-name: 阿里云短信测试
ali-sms-template: SMS_276490880
ali-sms-testing-template: SMS_154950909
ali-sms-access-id: LTAI5tJMkeZcEdtnkmaFCeR5
ali-sms-access-key: OzjF1JmFNwgEh2HN1eUehbMBEEguoj
ali-sms-region-id: cn-hangzhou